// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB683Efe-JTZneQrOyorqivA0UOp_ZK2XA',
    appId: '1:864649728752:web:5a68d569fffa5e9b452835',
    messagingSenderId: '864649728752',
    projectId: 'qrcode-9b8c5',
    authDomain: 'qrcode-9b8c5.firebaseapp.com',
    storageBucket: 'qrcode-9b8c5.firebasestorage.app',
    measurementId: 'G-88F1FM89QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrd5NosoIuTVYwS3yzdK0_cwefVt9xiZA',
    appId: '1:864649728752:android:9053d9709c11c652452835',
    messagingSenderId: '864649728752',
    projectId: 'qrcode-9b8c5',
    storageBucket: 'qrcode-9b8c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzKg3vUbwUEL-hgakOolqFD0-HFwPyb8',
    appId: '1:864649728752:ios:a1557df75de1169c452835',
    messagingSenderId: '864649728752',
    projectId: 'qrcode-9b8c5',
    storageBucket: 'qrcode-9b8c5.firebasestorage.app',
    iosBundleId: 'com.example.qrscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlzKg3vUbwUEL-hgakOolqFD0-HFwPyb8',
    appId: '1:864649728752:ios:a1557df75de1169c452835',
    messagingSenderId: '864649728752',
    projectId: 'qrcode-9b8c5',
    storageBucket: 'qrcode-9b8c5.firebasestorage.app',
    iosBundleId: 'com.example.qrscanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB683Efe-JTZneQrOyorqivA0UOp_ZK2XA',
    appId: '1:864649728752:web:1db7477bf7fd07ad452835',
    messagingSenderId: '864649728752',
    projectId: 'qrcode-9b8c5',
    authDomain: 'qrcode-9b8c5.firebaseapp.com',
    storageBucket: 'qrcode-9b8c5.firebasestorage.app',
    measurementId: 'G-MH9DYXEYMG',
  );
}
